In [249]:
import pandas as pd
import numpy as np
from tqdm import tqdm
from random import random, randrange, choice
from datetime import datetime, timedelta
from itertools import combinations
from pprint import pprint

import warnings
warnings.filterwarnings('ignore')

from IPython.core.interactiveshell import InteractiveShell 
InteractiveShell.ast_node_interactivity = "all" # Cell의 모든 반환값 출력

# 기본 데이터 세팅

In [250]:
블록원데이터 = pd.DataFrame({"블록명":["S1", "S2", "S3", "S4"], 
                    "중량": [50, 60, 30, 20], 
                    "가로": [10, 10, 5, 5], 
                    "세로":[10, 12, 6, 6], 
                    "표준공기":[2, 3, 1, 2], 
                    "납기":["2024-02-15", "2024-02-15", "2024-02-15", "2024-02-15"],
                    "정반배치":[0, 0, 0, 0]})
블록원데이터.head()

  블록명  중량  가로  세로  표준공기          납기  정반배치
0  S1  50  10  10     2  2024-02-15     0
1  S2  60  10  12     3  2024-02-15     0
2  S3  30   5   6     1  2024-02-15     0
3  S4  20   5   6     2  2024-02-15     0

In [251]:
정반원데이터 = pd.DataFrame({"정반명":["A", "B", "C"],
                   "가능중량":[100, 100, 30],
                   "가로":[10, 10, 5],
                   "세로":[20, 10, 10],
                   })
정반원데이터.head()

  정반명  가능중량  가로  세로
0   A   100  10  20
1   B   100  10  10
2   C    30   5  10

In [252]:
정반원데이터.index[정반원데이터["정반명"]=="B"].values[0]

1

In [253]:
start_date = datetime(2024, 2, 1)
end_date = datetime(2024, 2, 28)
날짜집합  = pd.date_range(start=start_date, end=end_date, freq='D')
날짜집합

DatetimeIndex(['2024-02-01', '2024-02-02', '2024-02-03', '2024-02-04',
               '2024-02-05', '2024-02-06', '2024-02-07', '2024-02-08',
               '2024-02-09', '2024-02-10', '2024-02-11', '2024-02-12',
               '2024-02-13', '2024-02-14', '2024-02-15', '2024-02-16',
               '2024-02-17', '2024-02-18', '2024-02-19', '2024-02-20',
               '2024-02-21', '2024-02-22', '2024-02-23', '2024-02-24',
               '2024-02-25', '2024-02-26', '2024-02-27', '2024-02-28'],
              dtype='datetime64[ns]', freq='D')

In [254]:
블록집합 = 블록원데이터["블록명"].unique().tolist()
블록집합

['S1', 'S2', 'S3', 'S4']

In [255]:
최초정반집합 = 정반원데이터["정반명"].unique().tolist()
최초정반집합

['A', 'B', 'C']

In [256]:
쌩전체경우의수 = len(날짜집합) * len(블록집합) * len(최초정반집합)
쌩전체경우의수

336

# 블록 데이터 전처리 함수

In [257]:
import functools
def unpack_df_columns(func):
    @functools.wraps(func)
    def _unpack_df_columns(*args, **kwargs):
        series = args[0]
        return func(*series.values)
    return _unpack_df_columns

In [262]:
@unpack_df_columns
def 최소착수요구일구하기(납기, 공기):
    result = pd.to_datetime(납기) - timedelta(days=int(공기))
    return result.date()

In [259]:
착수일가중치, 공기가중치, 크기가중치 = 0.7, 0.5, 0.5

@unpack_df_columns
def 블록우선순위구하기(날순, 공순, 크순):
    global 착수일가중치, 공기가중치, 크기가중치
    result = np.round((날순*착수일가중치 + 공순*공기가중치 + 크순*크기가중치)/3,1)
    return result

@unpack_df_columns
def 길이리스트만들기(길이1, 길이2):
    result = []
    가로 = max(길이1, 길이2)  
    세로 = min(길이1, 길이2)
    result.append(가로)
    result.append(가로)
    result.append(세로)
    result.append(세로)
    return result

In [265]:
def 블록데이터전처리(블록원데이터):
    df1 = 블록원데이터.copy()
    df1["납기"] = pd.to_datetime(df1["납기"])
    df1["면적"] = df1.eval("가로*세로")
    df1["최소착수요구일"] = df1[["납기", "표준공기"]].apply(최소착수요구일구하기, axis=1)
    df1["날짜순서"] = df1["최소착수요구일"].rank()
    df1["공기순서"] = df1["표준공기"].rank(ascending=False)
    df1["크기순서"] = df1["면적"].rank(ascending=False)
    df1["우선순위"] = df1[["날짜순서", "공기순서", "크기순서"]].apply(블록우선순위구하기, axis=1)
    df1["길이리스트"] = df1[["가로", "세로"]].apply(길이리스트만들기, axis=1)
    df1["최장길이"] = df1["길이리스트"].apply(lambda x : max(x))
    df1["최소길이"] = df1["길이리스트"].apply(lambda x : min(x))
    df1 = df1.drop(['가로', '세로'], axis=1)
    df1 = df1.sort_values(by=["우선순위"])
    return df1

In [266]:
df1 = 블록데이터전처리(블록원데이터)
df1

,블록명,중량,표준공기,납기,정반배치,면적,최소착수요구일,날짜순서,공기순서,크기순서,우선순위,길이리스트,최장길이,최소길이
1,S2,60,3,2024-02-15,0,120,2024-02-12,1.0,1.0,1.0,0.6,"[12, 12, 10, 10]",12,10
0,S1,50,2,2024-02-15,0,100,2024-02-13,2.5,2.5,2.0,1.3,"[10, 10, 10, 10]",10,10
3,S4,20,2,2024-02-15,0,30,2024-02-13,2.5,2.5,3.5,1.6,"[6, 6, 5, 5]",6,5
2,S3,30,1,2024-02-15,0,30,2024-02-14,4.0,4.0,3.5,2.2,"[6, 6, 5, 5]",6,5

In [58]:
공기가중치 = [9, 0.5]
크기가중치 = [0.5, 9]
착수일가중치 = 0.5
for 공기가중치, 크기가중치 in zip(공기가중치, 크기가중치):
    df2 = 블록데이터전처리(블록원데이터)
    print(df2[["블록명", "우선순위"]])

  블록명  우선순위
1  S2   3.3
0  S1   8.2
3  S4   8.5
2  S3  13.2
  블록명  우선순위
1  S2   3.3
0  S1   6.8
3  S4  11.3
2  S3  11.8

# 정반 데이터 전처리 함수

In [14]:
중량가중치, 크기가중치 = 0.5, 0.7

@unpack_df_columns
def 정반우선순위구하기(중순, 크순):
    global 중량가중치, 크기가중치
    result = np.round((중순*중량가중치 + 크순*크기가중치)/3,1)
    return result

def 면적리스트구하기(길이리스트):
    면적리스트 = []
    if 길이리스트[0] == 길이리스트[1]:
        면적리스트.append(길이리스트[0]*길이리스트[3])
    else:
        면적리스트  = []
        면적리스트.append(길이리스트[0]*길이리스트[3])
        면적리스트.append(길이리스트[1]*길이리스트[2])
    return 면적리스트

In [67]:
def 정반데이터전처리(정반원데이터):
    df = 정반원데이터.copy()
    
    df["정반구분"] = df["정반명"].apply(lambda x: x[:1])
    df["모정반"] = None
    df["길이리스트"] = df[["가로", "세로"]].apply(길이리스트만들기, axis=1)
    df["면적리스트"] = df["길이리스트"].apply(면적리스트구하기)
    df["평균면적"] = df["면적리스트"].apply(lambda x: np.mean(x))
    
    df["중량순서"] = df["가능중량"].rank(ascending=False)
    df["크기순서"] = df["평균면적"].rank(ascending=False)
    df["우선순위"] = df[["중량순서", "크기순서"]].apply(정반우선순위구하기, axis=1)
    
    df = df.drop(['가로', '세로'], axis=1)
    df = df.sort_values(by=["우선순위"])
    return df

In [210]:
df2 = 정반데이터전처리(정반원데이터)
df2

  정반명  가능중량 정반구분   모정반             길이리스트  면적리스트   평균면적  중량순서  크기순서  우선순위
0   A   100    A  None  [20, 20, 10, 10]  [200]  200.0   1.5   1.0   1.0
1   B   100    B  None  [10, 10, 10, 10]  [100]  100.0   1.5   2.0   2.0
2   C    30    C  None    [10, 10, 5, 5]   [50]   50.0   3.0   3.0   3.0

In [70]:
중량가중치들 = [0.9, 0.01]
크기가중치들 = [0.01, 3]

for 중량가중치, 크기가중치 in zip(중량가중치들, 크기가중치들):
    df2 = 정반데이터전처리(정반원데이터)
    print(df2[["정반구분", "정반명", "우선순위"]])

  정반구분 정반명  우선순위
0    A   A   0.5
1    B   B   0.5
2    C   C   0.9
  정반구분 정반명  우선순위
0    A   A   1.0
1    B   B   2.0
2    C   C   3.0

# 달력 함수 정의

## 배치달력함수

In [153]:
def create_init_calendar(시작년:int, 시작월:int, 종료년:int, 종료월:int, 정반집합):
    start_date = datetime(시작년, 시작월, 1)
    end_date = datetime(종료년, 종료월, 28)
    날짜집합  = pd.date_range(start=start_date, end=end_date, freq='D')
    
    배치달력 = pd.DataFrame()
    배치달력.index = 날짜집합
   
    for 정반 in 정반집합:
        배치달력[f"{정반}"] = 0

    return 배치달력

In [154]:
최초정반집합 = 정반원데이터["정반명"].unique().tolist()
배치달력 = create_init_calendar(2024, 2, 2024, 2, 최초정반집합)
배치달력

            A  B  C
2024-02-01  0  0  0
2024-02-02  0  0  0
2024-02-03  0  0  0
2024-02-04  0  0  0
2024-02-05  0  0  0
2024-02-06  0  0  0
2024-02-07  0  0  0
2024-02-08  0  0  0
2024-02-09  0  0  0
2024-02-10  0  0  0
2024-02-11  0  0  0
2024-02-12  0  0  0
2024-02-13  0  0  0
2024-02-14  0  0  0
2024-02-15  0  0  0
2024-02-16  0  0  0
2024-02-17  0  0  0
2024-02-18  0  0  0
2024-02-19  0  0  0
2024-02-20  0  0  0
2024-02-21  0  0  0
2024-02-22  0  0  0
2024-02-23  0  0  0
2024-02-24  0  0  0
2024-02-25  0  0  0
2024-02-26  0  0  0
2024-02-27  0  0  0
2024-02-28  0  0  0

In [155]:
def update_배치달력(배치달력, 정반명, 착수날짜, 필요공기, 정반집합):
    
    신규칼럼리스트 = 정반집합.copy()
#     print(f"배치달력칼럼리스트: {배치달력.columns}, 신규칼럼리스트: {신규칼럼리스트}")
    try:
        for 현칼럼 in 배치달력.columns:
            신규칼럼리스트.remove(현칼럼)  # 신규칼럼만 남기기 위해

        for 신규칼럼 in 신규칼럼리스트:
            # 신규칼럼에는 모정반의 배치달력 정보를 카피(모정반의 제약조건을 승계하도록)
            배치달력[f"{신규칼럼}"] = 배치달력[f"{신규칼럼[:1]}"]

        시점인덱스 = list(배치달력.index.strftime('%Y-%m-%d')).index(착수날짜)
        배치달력[f"{정반명}"].iloc[시점인덱스:시점인덱스+필요공기] = 1
        return 배치달력
    
    except:
        return 배치달력

## 공기달력 함수

In [156]:
def create_공기달력(배치달력, 날짜집합, 정반집합):
    total_list = []

    for 정반 in 정반집합:
        검토대상 = 배치달력[f"{정반}"].tolist()

        new_list = []
        new_num = 0
        for idx, i in enumerate(검토대상):
            if i == 0:
                new_num = new_num  + 1
                new_list.append(new_num)
            else:
                new_list.append(0)
                new_num = 0
        total_list.append(new_list)
        
    new_total = []
    for original_list in total_list:

        result_list = []
        group = []
        for num in original_list:
            if num == 0 and group:
                result_list.extend(reversed(group))
                group = []
            group.append(num)

        result_list.extend(reversed(group))

        new_total.append(result_list)

    공기달력 = pd.DataFrame()
    공기달력.index = 날짜집합

    for idx, 정반 in enumerate(정반집합):
        공기달력[f"{정반}"] =  new_total[idx]

    for 정반 in 정반집합:
        if 공기달력[f"{정반}"][0]== 0:
            공기달력[f"{정반}"] = 공기달력[f"{정반}"].shift(1)
        else:
            pass
    공기달력.fillna(0, inplace=True)
    return 공기달력

## 공백순서달력(first_zero) 함수

In [157]:
def create_공백순서달력(배치달력, 날짜집합):
    total = []
    정반집합 = 배치달력.columns.tolist()

    for 정반 in 배치달력.columns.tolist():
        
        input_list = 배치달력[f"{정반}"].tolist()
        
        counter = 1
        result_list = []

        for idx, x in enumerate(input_list):

            if idx == 0:
                if x == 1:
                    result_list.append(0)
                else:
                    result_list.append(counter)
                    counter += 1

            else:   
                if input_list[idx-1] == 1 and x == 0:
                    result_list.append(counter)
                    counter += 1
                else:
                    result_list.append(0)

        total.append(result_list)

    공백순서달력 = pd.DataFrame()
    공백순서달력.index = 날짜집합

    for idx, 정반 in enumerate(배치달력.columns.tolist()):
        공백순서달력[f"{정반}"] =  total[idx]

    return 공백순서달력

In [158]:
공백순서달력 = create_공백순서달력(배치달력, 날짜집합)
공백순서달력

            A  B  C
2024-02-01  1  1  1
2024-02-02  0  0  0
2024-02-03  0  0  0
2024-02-04  0  0  0
2024-02-05  0  0  0
2024-02-06  0  0  0
2024-02-07  0  0  0
2024-02-08  0  0  0
2024-02-09  0  0  0
2024-02-10  0  0  0
2024-02-11  0  0  0
2024-02-12  0  0  0
2024-02-13  0  0  0
2024-02-14  0  0  0
2024-02-15  0  0  0
2024-02-16  0  0  0
2024-02-17  0  0  0
2024-02-18  0  0  0
2024-02-19  0  0  0
2024-02-20  0  0  0
2024-02-21  0  0  0
2024-02-22  0  0  0
2024-02-23  0  0  0
2024-02-24  0  0  0
2024-02-25  0  0  0
2024-02-26  0  0  0
2024-02-27  0  0  0
2024-02-28  0  0  0

## 정반스펙달력함수

In [159]:
import ast
def string_to_list(string):
    my_list = ast.literal_eval(string)
    return my_list

In [160]:
def create_정반스펙달력(배치달력, 정반데이터):
    정반스펙달력 = 배치달력.copy()
    for idx, col in enumerate(배치달력.columns.tolist()):
        
        if 정반데이터[정반데이터["정반명"]==f"{col}"]["길이리스트"].values[0] != None:
            길이리스트 = 정반데이터[정반데이터["정반명"]==f"{col}"]["길이리스트"].values[0]
            길이리스트 = f"'{길이리스트}'"
            정반스펙달력.iloc[:,idx] = 길이리스트
            정반스펙달력[f'{col}'] = 정반스펙달력[f'{col}'].apply(string_to_list)
        else:
            길이리스트 = 정반데이터[정반데이터["정반명"]==f"{col}"]["길이리스트"].values[0]
            길이리스트 = f"'{길이리스트}'"
            정반스펙달력.iloc[:,idx] = 길이리스트
            정반스펙달력[f'{col}'] = 정반스펙달력[f'{col}'].apply(string_to_list)
    
    return 정반스펙달력

In [161]:
정반스펙달력 = create_정반스펙달력(배치달력, df2)
정반스펙달력

                           A                 B               C
2024-02-01  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-02  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-03  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-04  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-05  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-06  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-07  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-08  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-09  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-10  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-11  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-12  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-13  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-14  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-15  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-16  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-17  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-18  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-19  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-20  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-21  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-22  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-23  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-24  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-25  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-26  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-27  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-28  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]

In [163]:
def update_정반스펙달력(배치후공백순서달력, 정반스펙달력):
    for col in 배치후공백순서달력.columns.tolist():
        if len(col) != 1:
            공백발생일 = 배치후공백순서달력[배치후공백순서달력[f"{col}"]==1].index.strftime('%Y-%m-%d').values[0]
            날짜리스트 = 배치후공백순서달력.index.strftime('%Y-%m-%d').values
            공백발생일인덱스 = list(날짜리스트).index(공백발생일)
            칼럼리스트 = 배치후공백순서달력.columns.tolist()
            칼럼인덱스 = 칼럼리스트.index(col)
#             print(col, 공백발생일, 공백발생일인덱스, 칼럼인덱스)
            
            정반스펙달력.iloc[공백발생일인덱스:, 칼럼인덱스:칼럼인덱스+1] = None
    return 정반스펙달력

In [164]:
update_정반스펙달력(공백순서달력, 정반스펙달력)

                           A                 B               C
2024-02-01  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-02  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-03  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-04  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-05  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-06  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-07  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-08  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-09  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-10  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-11  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-12  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-13  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-14  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-15  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-16  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-17  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-18  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-19  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-20  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-21  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-22  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-23  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-24  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-25  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-26  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-27  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-28  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]

## 착수가능일찾기 함수

In [165]:
def 착수가능일찾기(공기달력, 공백순서달력, 정반, 표준공기):
    first_zeros = []
    
    for idx, i in enumerate(공백순서달력[f"{정반}"].tolist()):
        if i != 0:
            first_zeros.append(공백순서달력.index.strftime('%Y-%m-%d').values[idx])

    for idx, 착수가능일 in enumerate(first_zeros):
        착수가능일인덱스 = list(공기달력.index.strftime('%Y-%m-%d')).index(first_zeros[idx])
        착수가능일의확보가능공기 = 공기달력[f"{정반}"].iloc[착수가능일인덱스]
        
        if 착수가능일의확보가능공기 > 표준공기:
            return 착수가능일 
        else:
            pass

# 간트차트 함수

In [166]:
import plotly.express as px
def draw_gant(df):
    fig = px.timeline(
        
        df, 
        x_start="착수일", 
        x_end="종료일", 
        y="정반명",
        color="정반구분",
        hover_data = ["표준공기", "조립중량"],
        text = "차트텍스트",
        opacity=0.7
        )

    fig.update_yaxes(autorange="reversed")          #if not specified as 'reversed', the tasks will be listed from bottom up       
    fig.update_layout(
                    # title='Project Plan Gantt Chart',
                    hoverlabel_bgcolor='#DAEEED',   #Change the hover tooltip background color to a universal light blue color. If not specified, the background color will vary by team or completion pct, depending on what view the user chooses
                    bargap=0.2,
                    height=500,              
                    xaxis_title="", 
                    yaxis_title="정반명", 
                    font=dict(
                        family="Courier New, monospace",
                        size=12,  # Set the font size here
                        color="RebeccaPurple"
                        ),
    )
    fig.show()

# 달력생성 및 업데이트 연습

## 최초달력생성

In [167]:
배치달력 = create_init_calendar(2024, 2, 2024, 2, 최초정반집합)
배치달력.iloc[:2,:] = 1   ## 날짜 계산의 편의를 위해 초반 2일을 배치상태로 설정
배치달력

            A  B  C
2024-02-01  1  1  1
2024-02-02  1  1  1
2024-02-03  0  0  0
2024-02-04  0  0  0
2024-02-05  0  0  0
2024-02-06  0  0  0
2024-02-07  0  0  0
2024-02-08  0  0  0
2024-02-09  0  0  0
2024-02-10  0  0  0
2024-02-11  0  0  0
2024-02-12  0  0  0
2024-02-13  0  0  0
2024-02-14  0  0  0
2024-02-15  0  0  0
2024-02-16  0  0  0
2024-02-17  0  0  0
2024-02-18  0  0  0
2024-02-19  0  0  0
2024-02-20  0  0  0
2024-02-21  0  0  0
2024-02-22  0  0  0
2024-02-23  0  0  0
2024-02-24  0  0  0
2024-02-25  0  0  0
2024-02-26  0  0  0
2024-02-27  0  0  0
2024-02-28  0  0  0

In [168]:
정반집합 = 배치달력. columns.tolist()
공기달력 = create_공기달력(배치달력, 날짜집합, 정반집합)
공기달력

               A     B     C
2024-02-01   0.0   0.0   0.0
2024-02-02   0.0   0.0   0.0
2024-02-03  26.0  26.0  26.0
2024-02-04  25.0  25.0  25.0
2024-02-05  24.0  24.0  24.0
2024-02-06  23.0  23.0  23.0
2024-02-07  22.0  22.0  22.0
2024-02-08  21.0  21.0  21.0
2024-02-09  20.0  20.0  20.0
2024-02-10  19.0  19.0  19.0
2024-02-11  18.0  18.0  18.0
2024-02-12  17.0  17.0  17.0
2024-02-13  16.0  16.0  16.0
2024-02-14  15.0  15.0  15.0
2024-02-15  14.0  14.0  14.0
2024-02-16  13.0  13.0  13.0
2024-02-17  12.0  12.0  12.0
2024-02-18  11.0  11.0  11.0
2024-02-19  10.0  10.0  10.0
2024-02-20   9.0   9.0   9.0
2024-02-21   8.0   8.0   8.0
2024-02-22   7.0   7.0   7.0
2024-02-23   6.0   6.0   6.0
2024-02-24   5.0   5.0   5.0
2024-02-25   4.0   4.0   4.0
2024-02-26   3.0   3.0   3.0
2024-02-27   2.0   2.0   2.0
2024-02-28   1.0   1.0   1.0

In [170]:
공백순서달력 = create_공백순서달력(배치달력, 날짜집합)
공백순서달력

            A  B  C
2024-02-01  0  0  0
2024-02-02  0  0  0
2024-02-03  1  1  1
2024-02-04  0  0  0
2024-02-05  0  0  0
2024-02-06  0  0  0
2024-02-07  0  0  0
2024-02-08  0  0  0
2024-02-09  0  0  0
2024-02-10  0  0  0
2024-02-11  0  0  0
2024-02-12  0  0  0
2024-02-13  0  0  0
2024-02-14  0  0  0
2024-02-15  0  0  0
2024-02-16  0  0  0
2024-02-17  0  0  0
2024-02-18  0  0  0
2024-02-19  0  0  0
2024-02-20  0  0  0
2024-02-21  0  0  0
2024-02-22  0  0  0
2024-02-23  0  0  0
2024-02-24  0  0  0
2024-02-25  0  0  0
2024-02-26  0  0  0
2024-02-27  0  0  0
2024-02-28  0  0  0

In [171]:
정반스펙달력 = create_정반스펙달력(배치달력, df2)
정반스펙달력

                           A                 B               C
2024-02-01  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-02  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-03  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-04  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-05  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-06  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-07  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-08  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-09  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-10  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-11  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-12  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-13  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-14  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-15  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-16  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-17  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-18  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-19  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-20  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-21  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-22  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-23  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-24  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-25  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-26  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-27  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]
2024-02-28  [20, 20, 10, 10]  [10, 10, 10, 10]  [10, 10, 5, 5]

## 블록배치

In [172]:
착수가능일 = 착수가능일찾기(공기달력, 공백순서달력, "A", 13)
착수가능일

'2024-02-03'

## 달력 업데이트

In [173]:
새정반집합 = ["A","B","C","A_1"]
배치달력 = update_배치달력(배치달력, "A", "2024-02-03", 2, 새정반집합)
배치달력

            A  B  C  A_1
2024-02-01  1  1  1    1
2024-02-02  1  1  1    1
2024-02-03  1  0  0    0
2024-02-04  1  0  0    0
2024-02-05  0  0  0    0
2024-02-06  0  0  0    0
2024-02-07  0  0  0    0
2024-02-08  0  0  0    0
2024-02-09  0  0  0    0
2024-02-10  0  0  0    0
2024-02-11  0  0  0    0
2024-02-12  0  0  0    0
2024-02-13  0  0  0    0
2024-02-14  0  0  0    0
2024-02-15  0  0  0    0
2024-02-16  0  0  0    0
2024-02-17  0  0  0    0
2024-02-18  0  0  0    0
2024-02-19  0  0  0    0
2024-02-20  0  0  0    0
2024-02-21  0  0  0    0
2024-02-22  0  0  0    0
2024-02-23  0  0  0    0
2024-02-24  0  0  0    0
2024-02-25  0  0  0    0
2024-02-26  0  0  0    0
2024-02-27  0  0  0    0
2024-02-28  0  0  0    0

In [174]:
공기달력 = create_공기달력(배치달력, 날짜집합, 새정반집합)
공기달력

               A     B     C   A_1
2024-02-01   0.0   0.0   0.0   0.0
2024-02-02   0.0   0.0   0.0   0.0
2024-02-03   0.0  26.0  26.0  26.0
2024-02-04   0.0  25.0  25.0  25.0
2024-02-05  24.0  24.0  24.0  24.0
2024-02-06  23.0  23.0  23.0  23.0
2024-02-07  22.0  22.0  22.0  22.0
2024-02-08  21.0  21.0  21.0  21.0
2024-02-09  20.0  20.0  20.0  20.0
2024-02-10  19.0  19.0  19.0  19.0
2024-02-11  18.0  18.0  18.0  18.0
2024-02-12  17.0  17.0  17.0  17.0
2024-02-13  16.0  16.0  16.0  16.0
2024-02-14  15.0  15.0  15.0  15.0
2024-02-15  14.0  14.0  14.0  14.0
2024-02-16  13.0  13.0  13.0  13.0
2024-02-17  12.0  12.0  12.0  12.0
2024-02-18  11.0  11.0  11.0  11.0
2024-02-19  10.0  10.0  10.0  10.0
2024-02-20   9.0   9.0   9.0   9.0
2024-02-21   8.0   8.0   8.0   8.0
2024-02-22   7.0   7.0   7.0   7.0
2024-02-23   6.0   6.0   6.0   6.0
2024-02-24   5.0   5.0   5.0   5.0
2024-02-25   4.0   4.0   4.0   4.0
2024-02-26   3.0   3.0   3.0   3.0
2024-02-27   2.0   2.0   2.0   2.0
2024-02-28   1.0   1.0   1.0   1.0

In [176]:
공백순서달력 = create_공백순서달력(배치달력, 날짜집합)
공백순서달력

            A  B  C  A_1
2024-02-01  0  0  0    0
2024-02-02  0  0  0    0
2024-02-03  0  1  1    1
2024-02-04  0  0  0    0
2024-02-05  1  0  0    0
2024-02-06  0  0  0    0
2024-02-07  0  0  0    0
2024-02-08  0  0  0    0
2024-02-09  0  0  0    0
2024-02-10  0  0  0    0
2024-02-11  0  0  0    0
2024-02-12  0  0  0    0
2024-02-13  0  0  0    0
2024-02-14  0  0  0    0
2024-02-15  0  0  0    0
2024-02-16  0  0  0    0
2024-02-17  0  0  0    0
2024-02-18  0  0  0    0
2024-02-19  0  0  0    0
2024-02-20  0  0  0    0
2024-02-21  0  0  0    0
2024-02-22  0  0  0    0
2024-02-23  0  0  0    0
2024-02-24  0  0  0    0
2024-02-25  0  0  0    0
2024-02-26  0  0  0    0
2024-02-27  0  0  0    0
2024-02-28  0  0  0    0

# 물리적 스펙 적합도 검토

In [177]:
def get_면적리스트(길이리스트):
    result = []
    if 길이리스트[0] == 길이리스트[1]:
        면적 = 길이리스트[1] * 길이리스트[2]
        result.append(면적)
    else:
        면적1 = 길이리스트[0] * 길이리스트[3]
        면적2 = 길이리스트[1] * 길이리스트[2]
        result.append(면적1)
        result.append(면적2)
    result.sort(reverse=True)
    return result

In [178]:
def 면적_최장길이적합도_검토(정반길이리스트, 블록길이리스트):
    result = []
    블록최장길이 = max(블록길이리스트)
    블록최소길이 = min(블록길이리스트)
    블록면적 = get_면적리스트(블록길이리스트)[0]
    정반면적리스트 = get_면적리스트(정반길이리스트)
    try:
        for i in range(len(정반면적리스트)):
            if i == 0:
                if 정반면적리스트[i] >= 블록면적 and max(정반길이리스트[0], 정반길이리스트[3]) >= 블록최장길이 and min(정반길이리스트[0], 정반길이리스트[3]) >= 블록최소길이:
                    result.append("적합")
                else:
                    result.append("부적합")

            else:
                if 정반면적리스트[i] >= 블록면적 and max(정반길이리스트[1], 정반길이리스트[2]) >= 블록최장길이 and min(정반길이리스트[1], 정반길이리스트[2]) >= 블록최소길이:
                    result.append("적합")
                else:
                    result.append("부적합")

        return result
    except:
        return result

In [179]:
def 배치후정반길이리스트(정반길이리스트1, 블록길이리스트):
    정반길이리스트 = 정반길이리스트1.copy()
    
    블록최소길이 = min(블록길이리스트)
    블록최장길이 = max(블록길이리스트)
    정반최소길이 = min(정반길이리스트)
    정반최장길이 = max(정반길이리스트)
    
    if 정반최소길이 == 블록최소길이 and 정반최장길이 >= 블록최장길이:
        정반길이리스트[0] = max(정반길이리스트[0] - 블록최장길이,0)
        정반길이리스트[1] = max(정반길이리스트[1] - 블록최장길이,0)
        정반길이리스트[2] = 블록최소길이
        정반길이리스트[3] = 블록최소길이

    elif 정반최장길이 == 블록최장길이 and 정반최소길이 >= 블록최소길이:
        정반길이리스트[0] = 블록최장길이
        정반길이리스트[1] = 블록최장길이
        정반길이리스트[2] = max(정반길이리스트[2] - 블록최소길이,0)
        정반길이리스트[3] = max(정반길이리스트[3] - 블록최소길이,0)

    else:
        정반길이리스트[0] = max(정반길이리스트[0] - 블록최장길이,0)
        정반길이리스트[2] = max(정반길이리스트[2] - 블록최소길이,0)
    
    정반길이리스트 = [max([정반길이리스트[0], 정반길이리스트[3]]),
              max([정반길이리스트[1], 정반길이리스트[2]]),
              min([정반길이리스트[1], 정반길이리스트[2]]),
              min([정반길이리스트[0], 정반길이리스트[3]])]
    
    return 정반길이리스트

In [180]:
def get_새끼사각형(정반길이리스트):
    새끼사각형 = []
    사각형1 = [정반길이리스트[1], 정반길이리스트[1], 정반길이리스트[2], 정반길이리스트[2]]
    사각형2 = [정반길이리스트[0], 정반길이리스트[0], 정반길이리스트[3], 정반길이리스트[3]]
    for i in [사각형1, 사각형2]:
        if i not in 새끼사각형:
            새끼사각형.append(i)
    return 새끼사각형

In [181]:
def 복귀후정반길이리스트(정반길이리스트, 블록길이리스트):
    if 정반길이리스트[0] != 정반길이리스트[1]:
        정반긴길이 = 정반길이리스트[1]
        정반짧은길이 = 정반길이리스트[0]
        return [정반긴길이, 정반긴길이, 정반짧은길이, 정반짧은길이]
    else:
        정반긴길이 = 정반길이리스트[1]
        정반짧은길이 = 정반길이리스트[2] + 블록길이리스트[2]
        return [정반긴길이, 정반긴길이, 정반짧은길이, 정반짧은길이]

In [182]:
정반길이리스트 = [10, 10, 8, 8]
블록길이리스트 = [6, 6, 5, 5]

물리적적합도 = 면적_최장길이적합도_검토(정반길이리스트, 블록길이리스트)
print(f"물리적적합도: {물리적적합도}")
배치후결과 = 배치후정반길이리스트(정반길이리스트, 블록길이리스트)
print(f"배치후결과: {배치후결과}")

배치후새끼사각형 = get_새끼사각형(배치후결과)
print(f"배치후새끼사각형: {배치후새끼사각형}")

복귀후결과 = 복귀후정반길이리스트(배치후결과, 블록길이리스트)
print(f"복귀후결과: {복귀후결과}")

물리적적합도: ['적합']
배치후결과: [8, 10, 3, 4]
배치후새끼사각형: [[10, 10, 3, 3], [8, 8, 4, 4]]
복귀후결과: [10, 10, 8, 8]

# 생산계획수립 사전함수 정의

In [269]:
def 블록변수정리(블록데이터, target_block):
    블록 = dict()
    블록["인덱스"] =  블록데이터[블록데이터["블록명"]==target_block].index.values[0]
    블록["중량"] = 블록데이터[블록데이터["블록명"]==target_block]["중량"].values[0]
    블록["면적"] = 블록데이터[블록데이터["블록명"]==target_block]["면적"].values[0]
    블록["표준공기"] = 블록데이터[블록데이터["블록명"]==target_block]["표준공기"].values[0]
    블록["최소착수요구일"] = 블록데이터[블록데이터["블록명"]==target_block]["최소착수요구일"].values[0]
    블록["길이리스트"] = 블록데이터[블록데이터["블록명"]==target_block]["길이리스트"].values[0]
    return 블록

In [270]:
블록변수정리(df1, "S1")

{'인덱스': 0,
 '중량': 50,
 '면적': 100,
 '표준공기': 2,
 '최소착수요구일': datetime.date(2024, 2, 13),
 '길이리스트': [10, 10, 10, 10]}

In [348]:
def 정반변수정리(정반데이터, 정반명):
    정반 = dict()
    정반["가능중량"] = 정반데이터[정반데이터["정반명"]==정반명]["가능중량"].values[0]
    정반["길이리스트"] = 정반데이터[정반데이터["정반명"]==정반명]["길이리스트"].values[0]
    정반["면적리스트"] = 정반데이터[정반데이터["정반명"]==정반명]["면적리스트"].values[0]
    return 정반

In [313]:
A = 정반변수정리(df2, "A")
A

{'가능중량': 100, '길이리스트': [20, 20, 10, 10], '면적리스트': [200]}

In [314]:
새길이리스트 = [8, 3, 4, 5]
A["길이리스트"].append(새길이리스트)
A

{'가능중량': 100, '길이리스트': [20, 20, 10, 10, [8, 3, 4, 5]], '면적리스트': [200]}

In [315]:
def 날짜조건_가능정반dict_구하기(target_block, 블록데이터, 정반데이터, 수정정반리스트, 배치달력, 공기달력, 공백순서달력):
    # 배치달력, 공기달력, 공백순서달력, 정반데이터, 블록_size, 블록_weight, 블록_표준공기, least_start_date, 수정정반리스트
    
    블록변수 = 블록변수정리(블록데이터, target_block)
    블록표준공기 = 블록변수["표준공기"]
    최소착수요구일 = 블록변수["최소착수요구일"]
    print(f"블록명:{target_block}, 최소착수요구일:{최소착수요구일}, 블록표준공기:{블록표준공기}")
    
    가능정반_dict = {}
    for 정반 in 수정정반리스트:
        
        정반변수 = 정반변수정리(정반데이터, 정반)

        공백순서1인덱스 = list(공백순서달력[f"{정반}"]).index(1)
        공백순서1인덱스의날짜 = 배치달력.index[공백순서1인덱스]
        공백순서1인덱스의날짜의확보가능공기 = 공기달력[f"{정반}"][공백순서1인덱스]
        공백순서1인덱스날짜의공백순서 = 공백순서달력[f"{정반}"][공백순서1인덱스]
        print(f">>>[검토] 정반명:{정반}, 공백순서1인덱스의날짜: {공백순서1인덱스의날짜}, 인덱스: {공백순서1인덱스}, 확보가능공기:{공백순서1인덱스의날짜의확보가능공기}")

        try:
            공백순서2인덱스 = list(공백순서달력[f"{정반}"]).index(2)
            공백순서2인덱스의날짜 = 배치달력.index[공백순서2인덱스]
            공백순서2인덱스의날짜의확보가능공기 = 공기달력[f"{정반}"][공백순서2인덱스]
            공백순서2인덱스날짜의공백순서 = 공백순서달력[f"{정반}"][공백순서2인덱스]
            print(f">>>[검토] 정반명:{정반}, 공백순서2인덱스의날짜: {공백순서2인덱스의날짜}, 인덱스: {공백순서2인덱스}, 확보가능공기:{공백순서2인덱스의날짜의확보가능공기}")
            
            if 공백순서1인덱스의날짜 <= 최소착수요구일 and 공백순서1인덱스의날짜의확보가능공기 >= 블록표준공기 and 공백순서1인덱스날짜의공백순서 == 1:
                가능정반_dict[정반] = 공백순서1인덱스의날짜
            elif 공백순서2인덱스의날짜 <= 최소착수요구일 and 공백순서2인덱스의날짜의확보가능공기 >= 블록표준공기 and 공백순서2인덱스날짜의공백순서 == 2:
                가능정반_dict[정반] = 공백순서2인덱스의날짜
            else:
                pass

        except:
            if 공백순서1인덱스의날짜 <= 최소착수요구일 and 공백순서1인덱스의날짜의확보가능공기 >= 블록표준공기 and 공백순서1인덱스날짜의공백순서 == 1:
                가능정반_dict[정반] = 공백순서1인덱스의날짜
            else:
                pass
            pass

    return 가능정반_dict

In [316]:
수정정반리스트 = ["A", "B", "C"]
가능정반_dict = 날짜조건_가능정반dict_구하기("S1", df1, df2, 수정정반리스트, 배치달력, 공기달력, 공백순서달력)
가능정반_dict

블록명:S1, 최소착수요구일:2024-02-13, 블록표준공기:2
>>>[검토] 정반명:A, 공백순서1인덱스의날짜: 2024-02-05 00:00:00, 인덱스: 4, 확보가능공기:24.0
>>>[검토] 정반명:B, 공백순서1인덱스의날짜: 2024-02-03 00:00:00, 인덱스: 2, 확보가능공기:26.0
>>>[검토] 정반명:C, 공백순서1인덱스의날짜: 2024-02-03 00:00:00, 인덱스: 2, 확보가능공기:26.0

{'A': Timestamp('2024-02-05 00:00:00', freq='D'),
 'B': Timestamp('2024-02-03 00:00:00', freq='D'),
 'C': Timestamp('2024-02-03 00:00:00', freq='D')}

In [317]:
def 최선조기착수가능정반(가능정반_dict):
    최선조기착수가능정반 = [key for key, value in 가능정반_dict.items() if value == min(가능정반_dict.values())]
    return 최선조기착수가능정반

In [318]:
최선조기착수가능정반 = 최선조기착수가능정반(가능정반_dict)
최선조기착수가능정반

['B', 'C']

In [346]:
def get_물리적스펙가능정반(최선조기착수가능정반, 정반데이터, target_block, 블록데이터):
    
    블록변수 = 블록변수정리(블록데이터, target_block)
    블록면적 = 블록변수["면적"]
    블록중량 = 블록변수["중량"]
    블록길이리스트 = 블록변수["길이리스트"]
    블록최장길이 = max(블록길이리스트)
    블록최소길이 = min(블록길이리스트)
    
    print(f"* 블록명:{target_block}, 블록중량:{블록중량}, 블록면적:{블록면적}, 길이리스트:{블록길이리스트}, 블록최장길이:{블록최장길이}, 블록최소길이:{블록최소길이}")
    print()

    물리적스펙가능정반 = []
    
    for 후보정반 in 최선조기착수가능정반:
        후보정반변수 = 정반변수정리(정반데이터, 후보정반)
        가능중량 = 후보정반변수["가능중량"]
        정반면적리스트 = 후보정반변수["면적리스트"]
        정반길이리스트 = 후보정반변수["길이리스트"]
        정반최장길이 = max(정반길이리스트)
        정반최소길이 = min(정반길이리스트)
        print(f"* 정반명:{후보정반},  가능중량:{가능중량}, 길이리스트:{정반길이리스트}, 면적리스트:{정반면적리스트}")

        ## 물리적 적합도 검토 ##############################
        
        물리적적합도리스트 = 면적_최장길이적합도_검토(정반길이리스트, 블록길이리스트)
        print(f">>>[검토]{후보정반}정반의 면적_최장길이 적합도 함수 체크")
        print(f">>>[검토]정반 {후보정반}의 면적/사이즈 배치가능 여부:{물리적적합도리스트} / 정반가능중량:{가능중량} 정반면적리스트:{정반면적리스트}, 길이리스트:{정반길이리스트}")
        print()

        if "적합" in 물리적적합도리스트:
            물리적스펙가능정반.append(후보정반)
        else:
            pass
    return 물리적스펙가능정반

In [349]:
물리적스펙가능정반 = get_물리적스펙가능정반(최선조기착수가능정반, df2, "S1", df1)
물리적스펙가능정반

* 블록명:S1, 블록중량:50, 블록면적:100, 길이리스트:[10, 10, 10, 10], 블록최장길이:10, 블록최소길이:10

* 정반명:B,  가능중량:100, 길이리스트:[10, 10, 10, 10], 면적리스트:[100]
>>>[검토]B정반의 면적_최장길이 적합도 함수 체크
>>>[검토]정반 B의 면적/사이즈 배치가능 여부:['적합'] / 정반가능중량:100 정반면적리스트:[100], 길이리스트:[10, 10, 10, 10]

* 정반명:C,  가능중량:30, 길이리스트:[10, 10, 5, 5], 면적리스트:[50]
>>>[검토]C정반의 면적_최장길이 적합도 함수 체크
>>>[검토]정반 C의 면적/사이즈 배치가능 여부:['부적합'] / 정반가능중량:30 정반면적리스트:[50], 길이리스트:[10, 10, 5, 5]

['B']

In [417]:
def get_수정정반리스트(물리적스펙가능정반, 정반쪼개는면적_Thresh, 정반데이터,수정정반리스트, 블록데이터, target_block):
    
    블록변수 = 블록변수정리(블록데이터, target_block)
    블록길이리스트 = 블록변수["길이리스트"]
    
    랜덤최선정반 = choice(물리적스펙가능정반)
    
    랜덤최선정반변수 = 정반변수정리(정반데이터, 랜덤최선정반)
    랜덤정반길이리스트 = 랜덤최선정반변수["길이리스트"]
    랜덤정반면적리스트 = 랜덤최선정반변수["면적리스트"]
    새끼사각형길이리스트 = get_새끼사각형(랜덤정반길이리스트)
    새끼사각형면적리스트 = [get_면적리스트(리스트)for 리스트 in 새끼사각형길이리스트]
    print(f"랜덤최선정반: {랜덤최선정반}, 길이리스트:{랜덤정반길이리스트}, 새끼사각형길이:{새끼사각형길이리스트}, 새끼사각형면적리스트:{새끼사각형면적리스트}")
    
    # 랜덤최선정반의 새끼사각형 정의
    새끼사각형 = dict()
    for key, value in zip(새끼사각형면적리스트, 새끼사각형길이리스트):
        print(key, value)
        새끼사각형[key[0]] = value
        
    print(f"새끼사각형: {새끼사각형}")
    
    작은사각형_key = min(새끼사각형.keys())
    작은사각형길이리스트 = 새끼사각형[작은사각형_key]
    print(f"작은사각형_key: {작은사각형_key}, 길이리스트: {작은사각형길이리스트}")
    
    큰사각형_key = max(새끼사각형.keys())
    큰사각형길이리스트 = 새끼사각형[큰사각형_key]
    print(f"큰사각형_key: {큰사각형_key}, 길이리스트: {큰사각형길이리스트}")
    
    
    작은사각형_적합도체크 = 면적_최장길이적합도_검토(작은사각형길이리스트, 블록길이리스트)[0]
    print(f"작은사각형_적합도체크: {작은사각형_적합도체크}")
    
    if 작은사각형_적합도체크 == "적합":
        
        작은사각형_정반_명칭 = 랜덤최선정반 + f"_{randrange(100)}"
        정반데이터.loc[len(정반데이터)] = {
            "정반명": 작은사각형_정반_명칭,
            "가능중량": 랜덤최선정반변수["가능중량"],
            "정반구분":작은사각형_정반_명칭[:1],
            "모정반": 랜덤최선정반,
            "길이리스트": 작은사각형길이리스트,
            "면적리스트": get_면적리스트(작은사각형길이리스트),
            "평균면적": np.mean(get_면적리스트(작은사각형길이리스트))
        }
        
        print(정반데이터)

In [418]:
get_수정정반리스트(물리적스펙가능정반, 0.3, df2, 수정정반리스트, df1, "S1")

랜덤최선정반: B, 길이리스트:[10, 10, 10, 10], 새끼사각형길이:[[10, 10, 10, 10]], 새끼사각형면적리스트:[[100]]
[100] [10, 10, 10, 10]
새끼사각형: {100: [10, 10, 10, 10]}
작은사각형_key: 100, 길이리스트: [10, 10, 10, 10]
큰사각형_key: 100, 길이리스트: [10, 10, 10, 10]
작은사각형_적합도체크: 적합
   정반명  가능중량 정반구분   모정반                           길이리스트  면적리스트   평균면적  중량순서  \
0    A   100    A  None  [20, 20, 10, 10, [8, 3, 4, 5]]  [200]  200.0   1.5
1    B   100    B  None                [10, 10, 10, 10]  [100]  100.0   1.5
2    C    30    C  None                  [10, 10, 5, 5]   [50]   50.0   3.0
3  B_5   100    B     B                [10, 10, 10, 10]  [100]  100.0   NaN

   크기순서  우선순위
0   1.0   1.0
1   2.0   2.0
2   3.0   3.0
3   NaN   NaN

In [323]:
def get_수정정반리스트(랜덤정반인덱스, 정반쪼개는면적_Thresh, 잔여면적비율, 랜덤최선정반, 블록_길이리스트, 정반데이터, 수정정반리스트, 자식정반고유번호):
    
    

    if 잔여면적비율 >= 정반쪼개는면적_Thresh:
        
        정반면적 = 정반데이터[정반데이터["정반명"]==랜덤최선정반]["사이즈"].values[0] 
        weight_capa = 정반데이터[정반데이터["정반명"]==랜덤최선정반]["가능중량"].values[0]
        
        새정반이름 = 랜덤최선정반+f"_{randrange(100)}"
#         자식정반고유번호 += 1
        새정반면적 = 정반면적 * 잔여면적비율
        기존정반새면적 = 정반면적 - 새정반면적
        가능정반인덱스 = 정반데이터[정반데이터["정반명"]==랜덤최선정반].index.values[0]
        원정반길이리스트 = 정반데이터[정반데이터["정반명"]==랜덤최선정반]["원길이리스트"].values[0]
                
        if len(랜덤최선정반) == 1:
            정반길이리스트 = 정반데이터[정반데이터["정반명"]==랜덤최선정반]["원길이리스트"].values[0]
        else:
            정반길이리스트 = 정반데이터[정반데이터["정반명"]==랜덤최선정반]["수정길이리스트"].values[0]

        ### 분할 자식정반 스펙 계산 ################
        새정반길이리스트 = 배치후잔여정반길이리스트(정반길이리스트, 블록_길이리스트)
        새정반최장길이 = max(새정반길이리스트)
        새정반최소길이 = min(새정반길이리스트)
        새정반면적리스트 = 면적리스트구하기(새정반길이리스트)

        정반데이터.loc[len(정반데이터)] = {"정반명":새정반이름, "가능중량": weight_capa, "사이즈":새정반면적, 
                                 "원길이리스트":새정반길이리스트, "원최장길이":새정반최장길이,"원최소길이":새정반최소길이, "원면적리스트":새정반면적리스트,
                                 "수정길이리스트":새정반길이리스트, "수정최장길이":새정반최장길이,"수정최소길이":새정반최소길이, "수정면적리스트":새정반면적리스트}

        정반데이터["중량순서"] = 정반데이터["가능중량"].rank(ascending=False)
        정반데이터["크기순서"] = 정반데이터["사이즈"].rank(ascending=False)
        정반데이터["우선순위"] = 정반데이터[["중량순서", "크기순서"]].apply(정반우선순위구하기, axis=1)
        정반데이터 = 정반데이터.sort_values(by=["우선순위"])
        정반데이터["정반구분"] = 정반데이터["정반명"].apply(lambda x: x[:1])

        print(f">>>잔여면적비율 {np.round(잔여면적비율,1)*100}%로 30% 이상이므로 정반 쪼개기 - 자식정반이름 :{새정반이름} / 자식정반면적:{np.round(새정반면적,1)} / 엄마정반면적: {np.round(기존정반새면적,1)}") 
        print(f"*** 새정반길이리스트: {새정반길이리스트}")
        print()
        
        수정정반리스트.append(새정반이름)  

    else:
        print(f">>>1순위 정반의 잔여면적비율({np.round(잔여면적비율,1)}이 Thresh({정반쪼개는면적_Thresh}) 비율보다 작아 쪼갤 수 없습니다.")
        print()
        
    return 수정정반리스트, 정반데이터

# 생산계획수립

In [324]:
def 생산계획수립(블록데이터, 정반데이터, 배치달력, 정반쪼개는면적_Thresh):
    ##--------------------------------------------------------------------------------------------------
    # 결과모음리스트 
    배정된블록 = []
    배정된정반 = []
    착수일 = []
    표준공기 = []
    종료일 = []
    조립중량  = []
    
    # Initial Variables settings
    자식정반고유번호 = 0
    수정블록리스트 = 블록데이터["블록명"].tolist()
    수정정반리스트 = 정반데이터["정반명"].tolist()
    공기달력 = create_공기달력(배치달력, 날짜집합, 수정정반리스트)
    공백순서달력 = create_공백순서달력(배치달력, 수정정반리스트, 날짜집합)
    정반스펙달력 = create_정반스펙달력(배치달력, 정반데이터)
    ##----------------------------------------------------------------------------------------------------------
    
    for _ in tqdm(range(len(수정블록리스트))):
        if 수정블록리스트:
            target_block = 수정블록리스트[0]
        else:
            print("수정블록리스트에 검토대상 잔여블록이 없습니다.")
            print()
            break
        ##------------------------------------------------------------------------------------------    
        블록인덱스 = 블록데이터[블록데이터["블록명"]==target_block].index.values[0]
        블록_weight = 블록데이터[블록데이터["블록명"]==target_block]["중량"].values[0]
        블록_size = 블록데이터[블록데이터["블록명"]==target_block]["사이즈"].values[0]
        least_start_date = 블록데이터[블록데이터["블록명"]==target_block]["최소요구착수일"].values[0]
        블록_표준공기 = 블록데이터[블록데이터["블록명"]==target_block]["표준공기"].values[0]
        블록_길이리스트 = 블록데이터[블록데이터["블록명"]==target_block]["길이리스트"].values[0]
        블록_최장길이 = 블록데이터[블록데이터["블록명"]==target_block]["최장길이"].values[0]
        블록_최소길이 = 블록데이터[블록데이터["블록명"]==target_block]["최소길이"].values[0]
        print()
        print(f"*** 타겟블록-name:{target_block},weight:{블록_weight},size:{블록_size},길이리스트:{블록_길이리스트},최장길이:{블록_최장길이},최소길이:{블록_최소길이},최소착수요구일:{least_start_date},표준공기:{블록_표준공기}")
        print()
        ##-------------------------------------------------------------------------------------------------------------
        
        ### 달력기준 가능 정반 dict 구하기 ############################################################
        가능정반_dict = 가능정반dict_구하기(배치달력, 공기달력, 공백순서달력, 정반스펙달력, 정반데이터, 블록_size, 블록_weight, 블록_표준공기, least_start_date, 수정정반리스트)
        ################################################################################################
        
        if 가능정반_dict != {}:
            print(f"*** 가능정반 :{가능정반_dict}")
            최선조기착수가능정반 = [key for key, value in 가능정반_dict.items() if value == min(가능정반_dict.values())]   # 여러개일수 있으므로 리스트로 반환
            print(f"*** 최선조기착수 가능정반:{min(가능정반_dict.values())} ---> {최선조기착수가능정반}")  
            print()
            
            ### 물리적 스펙 가능 검토 #########################################################################
            물리적스펙가능정반 = get_물리적스펙가능정반(최선조기착수가능정반, 정반데이터, 블록_size, 블록_길이리스트, 블록_최장길이, 블록_최소길이)
            print(f"*** 물리적 스펙 가능 정반: {물리적스펙가능정반}")
            print()
            ####################################################################################################
            
            if 물리적스펙가능정반:
                
                랜덤최선정반 = choice(물리적스펙가능정반)
                
                if len(랜덤최선정반) == 1:
                    랜덤정반인덱스 = 정반데이터.index[정반데이터["정반명"]==랜덤최선정반].values[0]
                    랜덤정반최장길이 = 정반데이터[정반데이터["정반명"]==랜덤최선정반]["원최장길이"].values[0]
                    랜덤정반길이리스트 = 정반데이터[정반데이터["정반명"]==랜덤최선정반]["원길이리스트"].values[0]
                    랜덤정반면적리스트 = 정반데이터[정반데이터["정반명"]==랜덤최선정반]["원면적리스트"].values[0]
                    랜덤정반면적 = min(랜덤정반면적리스트)
                else:
                    랜덤정반인덱스 = 정반데이터.index[정반데이터["정반명"]==랜덤최선정반].values[0]
                    랜덤정반최장길이 = 정반데이터[정반데이터["정반명"]==랜덤최선정반]["수정최장길이"].values[0]
                    랜덤정반길이리스트 = 정반데이터[정반데이터["정반명"]==랜덤최선정반]["수정길이리스트"].values[0]
                    랜덤정반면적리스트 = 정반데이터[정반데이터["정반명"]==랜덤최선정반]["수정면적리스트"].values[0]
                    랜덤정반면적 = min(랜덤정반면적리스트)
                
                
                잔여면적 = 랜덤정반면적 - 블록_size
                잔여면적비율 = 잔여면적 / 랜덤정반면적
                print(f"*** 랜덤선택최선정반:{랜덤최선정반}")
                print(f"*** 랜덤정반스펙- 길이리스트:{랜덤정반길이리스트}, 면적리스트:{랜덤정반면적리스트}, MIN면적:{랜덤정반면적}, block_size:{블록_size}, 잔여면적:{잔여면적}, 잔여면적비율:{np.round(잔여면적비율,2)}")
                print()
                                
                ### 자식정반분할후 수정정반리스트 구하기 ##############################################
                함수결과 = get_수정정반리스트(랜덤정반인덱스, 정반쪼개는면적_Thresh, 잔여면적비율, 랜덤최선정반, 블록_길이리스트, 정반데이터, 수정정반리스트, 자식정반고유번호)
                수정정반리스트 = 함수결과[0]
                정반데이터 = 함수결과[1]
                print(f"*** 수정정반리스트: {수정정반리스트}")
                ########################################################################################
                            
                착수가능일 = 착수가능일찾기(공기달력, 공백순서달력, 랜덤최선정반, 블록_표준공기)
                블록데이터.loc[블록인덱스, "정반배치"] = 1

                배정결과 = {"블록명": target_block, "정반명": 랜덤최선정반, "착수일": 착수가능일}   
                print(f"*** 최종배정결과 : {배정결과}") 
                print()

                배정된블록.append(target_block)
                배정된정반.append(랜덤최선정반)
                print(f"???????????배정된정반: {배정된정반}")
                착수일.append(착수가능일)
                표준공기.append(블록_표준공기)
                original_date = datetime.strptime(착수가능일, "%Y-%m-%d")
                종료날짜 = original_date + timedelta(days=int(블록_표준공기)) 
                종료날짜 = 종료날짜.strftime("%Y-%m-%d")
                종료일.append(종료날짜)
                조립중량.append(블록_weight)

                print(f"(블록배치전) 수정블록리스트 : {수정블록리스트}, 수정정반리스트 : {수정정반리스트}")
                수정블록리스트.remove(target_block) 
                print(f"(블록배치후) 수정블록리스트 : {수정블록리스트}, 수정정반리스트 : {수정정반리스트}")
                print("="*90)            
                
                ##### 달력 1차 업데이트 ############
                배치달력 =  update_배치달력(배치달력, 랜덤최선정반, 착수가능일, 블록_표준공기, 수정정반리스트) 
                공기달력 = create_공기달력(배치달력, 날짜집합, 수정정반리스트)
                공백순서달력 = create_공백순서달력(배치달력, 수정정반리스트, 날짜집합)
                정반스펙달력 = create_정반스펙달력(배치달력, 정반데이터)
                정반스펙달력 = update_정반스펙달력(공백순서달력, 정반스펙달력)
                
            else:
                print("★ 물리적 스펙상 배치가능한 정반이 없습니다.!!!!")
                print("="*50)
                수정블록리스트.remove(target_block)
                pass
        else:
            print("★ 날짜 조건에 따른 배치가능한 정반이 없습니다.!!!!")
            print("="*50)
            수정블록리스트.remove(target_block)
            pass

    최종배정결과 = pd.DataFrame({"블록명":배정된블록, "정반명":배정된정반, "착수일":착수일, "표준공기":표준공기, "종료일": 종료일, "조립중량": 조립중량})
    최종배정결과["정반구분"] = 최종배정결과["정반명"].apply(lambda x: x[:1])
    return 최종배정결과, 블록데이터, 정반데이터, 배치달력, 공기달력, 공백순서달력, 정반스펙달력

# 배치 시뮬레이션

In [138]:
data_num = 2
착수일가중치, 공기가중치, 크기가중치 = 0.7, 0.5, 0.5
중량가중치, 크기가중치 = 0.5, 0.7

블록원데이터 = pd.read_excel(f"./data/data{data_num}.xlsx", sheet_name="블록데이터")
정반원데이터 = pd.read_excel(f"./data/data{data_num}.xlsx", sheet_name="정반데이터")

블록데이터 = 블록데이터전처리(블록원데이터)
정반데이터 = 정반데이터전처리(정반원데이터)
최초정반집합 = 정반원데이터["정반명"].unique().tolist()

배치달력 = create_init_calendar(2024, 2, 2024, 2, 최초정반집합) 
배치달력.iloc[:2,:] = 1   ## 날짜 계산의 편의를 위해 초반 2일을 배치상태로 설정

result = 생산계획수립(블록데이터, 정반데이터, 배치달력, 0.3)

 50%|█████████████████████████████████                                 | 4/8 [00:00<00:00, 38.82it/s]

*** 타겟블록-name:S6,weight:50,size:120,길이리스트:[12, 12, 10, 10],최장길이:12,최소길이:10,최소착수요구일:2024-02-05,표준공기:6

*** 가능정반 :{'A': Timestamp('2024-02-03 00:00:00', freq='D'), 'B': Timestamp('2024-02-03 00:00:00', freq='D')}
*** 최선조기착수 가능정반:2024-02-03 00:00:00 ---> ['A', 'B']

>>>A정반의 면적_최장길이 적합도 함수 체크
>>>>>정반면적리스트:[200], 정반길이리스트:[20, 20, 10, 10], 블록사이즈:120, 블록최장길이:12, 블록최단길이:10
>>>>>정반 A의 면적/사이즈 배치가능 여부:['적합'] / 정반가능중량:100 정반면적:200, 길이리스트:[20, 20, 10, 10], 정반최장길이:20

>>>B정반의 면적_최장길이 적합도 함수 체크
>>>>>정반면적리스트:[150], 정반길이리스트:[15, 15, 10, 10], 블록사이즈:120, 블록최장길이:12, 블록최단길이:10
>>>>>정반 B의 면적/사이즈 배치가능 여부:['적합'] / 정반가능중량:100 정반면적:150, 길이리스트:[15, 15, 10, 10], 정반최장길이:15

*** 물리적 스펙 가능 정반: ['A', 'B']

*** 랜덤선택최선정반:B
*** 랜덤정반스펙- 길이리스트:[15, 15, 10, 10], 면적리스트:[150], MIN면적:150, block_size:120, 잔여면적:30, 잔여면적비율:0.2

>>>1순위 정반의 잔여면적비율(0.2이 Thresh(0.3) 비율보다 작아 쪼갤 수 없습니다.

*** 수정정반리스트: ['A', 'B', 'C']
*** 최종배정결과 : {'블록명': 'S6', '정반명': 'B', '착수일': '2024-02-03'}

???????????배정된정반: ['B']
(블록배치전) 수정블록리스트 : ['S6', 'S2', 'S5', 'S8', 'S4', 'S1', 'S3', 'S7'], 수정정반리스트 : ['A', 'B', 'C']
(블록배치후) 수정블록리스트 : ['S2', 'S5', 'S8', 'S4', 'S1', 'S3', 'S7'], 수정정반리스트 : ['A', 'B', 'C']
==========================================================================================

*** 타겟블록-name:S2,weight:60,size:120,길이리스트:[12, 12, 10, 10],최장길이:12,최소길이:10,최소착수요구일:2024-02-06,표준공기:6

*** 가능정반 :{'A': Timestamp('2024-02-03 00:00:00', freq='D')}
*** 최선조기착수 가능정반:2024-02-03 00:00:00 ---> ['A']

>>>A정반의 면적_최장길이 적합도 함수 체크
>>>>>정반면적리스트:[200], 정반길이리스트:[20, 20, 10, 10], 블록사이즈:120, 블록최장길이:12, 블록최단길이:10
>>>>>정반 A의 면적/사이즈 배치가능 여부:['적합'] / 정반가능중량:100 정반면적:200, 길이리스트:[20, 20, 10, 10], 정반최장길이:20

*** 물리적 스펙 가능 정반: ['A']

*** 랜덤선택최선정반:A
*** 랜덤정반스펙- 길이리스트:[20, 20, 10, 10], 면적리스트:[200], MIN면적:200, block_size:120, 잔여면적:80, 잔여면적비율:0.4

>>>잔여면적비율 40.0%로 30% 이상이므로 정반 쪼개기 - 자식정반이름 :A_29 / 자식정반면적:80.0 / 엄마정반면적: 120.0
*** 새정반길이리스트: [10, 10, 8, 8]

*** 수정정반리스트: ['A', 'B', 'C', 'A_29']
*** 최종배정결과 : {'블록명': 'S2', '정반명': 'A', '착수일': '2024-02-03'}

???????????배정된정반: ['B', 'A']
(블록배치전) 수정블록리스트 : ['S2', 'S5', 'S8', 'S4', 'S1', 'S3', 'S7'], 수정정반리스트 : ['A', 'B', 'C', 'A_29']
(블록배치후) 수정블록리스트 : ['S5', 'S8', 'S4', 'S1', 'S3', 'S7'], 수정정반리스트 : ['A', 'B', 'C', 'A_29']
==========================================================================================

*** 타겟블록-name:S5,weight:50,size:120,길이리스트:[12, 12, 10, 10],최장길이:12,최소길이:10,최소착수요구일:2024-02-08,표준공기:7

★ 날짜 조건에 따른 배치가능한 정반이 없습니다.!!!!
==================================================

*** 타겟블록-name:S8,weight:60,size:120,길이리스트:[12, 12, 10, 10],최장길이:12,최소길이:10,최소착수요구일:2024-02-22,표준공기:6

*** 가능정반 :{'A': Timestamp('2024-02-09 00:00:00', freq='D'), 'B': Timestamp('2024-02-09 00:00:00', freq='D')}
*** 최선조기착수 가능정반:2024-02-09 00:00:00 ---> ['A', 'B']

>>>A정반의 면적_최장길이 적합도 함수 체크
>>>>>정반면적리스트:[200], 정반길이리스트:[20, 20, 10, 10], 블록사이즈:120, 블록최장길이:12, 블록최단길이:10
>>>>>정반 A의 면적/사이즈 배치가능 여부:['적합'] / 정반가능중량:100 정반면적:200.0, 길이리스트:[20, 20, 10, 10], 정반최장길이:20

>>>B정반의 면적_최장길이 적합도 함수 체크
>>>>>정반면적리스트:[150], 정반길이리스트:[15, 15, 10, 10], 블록사이즈:120, 블록최장길이:12, 블록최단길이:10
>>>>>정반 B의 면적/사이즈 배치가능 여부:['적합'] / 정반가능중량:100 정반면적:150.0, 길이리스트:[15, 15, 10, 10], 정반최장길이:15

*** 물리적 스펙 가능 정반: ['A', 'B']

*** 랜덤선택최선정반:A
*** 랜덤정반스펙- 길이리스트:[20, 20, 10, 10], 면적리스트:[200], MIN면적:200, block_size:120, 잔여면적:80, 잔여면적비율:0.4

>>>잔여면적비율 40.0%로 30% 이상이므로 정반 쪼개기 - 자식정반이름 :A_98 / 자식정반면적:80.0 / 엄마정반면적: 120.0
*** 새정반길이리스트: [10, 10, 8, 8]

*** 수정정반리스트: ['A', 'B', 'C', 'A_29', 'A_98']
*** 최종배정결과 : {'블록명': 'S8', '정반명': 'A', '착수일': '2024-02-09'}

???????????배정된정반: ['B', 'A', 'A']
(블록배치전) 수정블록리스트 : ['S8', 'S4', 'S1', 'S3', 'S7'], 수정정반리스트 : ['A', 'B', 'C', 'A_29', 'A_98']
(블록배치후) 수정블록리스트 : ['S4', 'S1', 'S3', 'S7'], 수정정반리스트 : ['A', 'B', 'C', 'A_29', 'A_98']
==========================================================================================

*** 타겟블록-name:S4,weight:20,size:30,길이리스트:[6, 6, 5, 5],최장길이:6,최소길이:5,최소착수요구일:2024-02-03,표준공기:3

*** 가능정반 :{'C': Timestamp('2024-02-03 00:00:00', freq='D'), 'A_29': Timestamp('2024-02-03 00:00:00', freq='D')}
*** 최선조기착수 가능정반:2024-02-03 00:00:00 ---> ['C', 'A_29']

>>>C정반의 면적_최장길이 적합도 함수 체크
>>>>>정반면적리스트:[50], 정반길이리스트:[10, 10, 5, 5], 블록사이즈:30, 블록최장길이:6, 블록최단길이:5
>>>>>정반 C의 면적/사이즈 배치가능 여부:['적합'] / 정반가능중량:30 정반면적:50.0, 길이리스트:[10, 10, 5, 5], 정반최장길이:10

>>>A_29정반의 면적_최장길이 적합도 함수 체크
>>>>>정반면적리스트:[80], 정반길이리스트:[10, 10, 8, 8], 블록사이즈:30, 블록최장길이:6, 블록최단길이:5
>>>>>정반 A_29의 면적/사이즈 배치가능 여부:['적합'] / 정반가능중량:100 정반면적:80.0, 길이리스트:[10, 10, 8, 8], 정반최장길이:10

*** 물리적 스펙 가능 정반: ['C', 'A_29']

*** 랜덤선택최선정반:C
*** 랜덤정반스펙- 길이리스트:[10, 10, 5, 5], 면적리스트:[50], MIN면적:50, block_size:30, 잔여면적:20, 잔여면적비율:0.4

>>>잔여면적비율 40.0%로 30% 이상이므로 정반 쪼개기 - 자식정반이름 :C_73 / 자식정반면적:20.0 / 엄마정반면적: 30.0
*** 새정반길이리스트: [5, 5, 4, 4]

*** 수정정반리스트: ['A', 'B', 'C', 'A_29', 'A_98', 'C_73']
*** 최종배정결과 : {'블록명': 'S4', '정반명': 'C', '착수일': '2024-02-03'}

???????????배정된정반: ['B', 'A', 'A', 'C']
(블록배치전) 수정블록리스트 : ['S4', 'S1', 'S3', 'S7'], 수정정반리스트 : ['A', 'B', 'C', 'A_29', 'A_98', 'C_73']
(블록배치후) 수정블록리스트 : ['S1', 'S3', 'S7'], 수정정반리스트 : ['A', 'B', 'C', 'A_29', 'A_98', 'C_73']
==========================================================================================

*** 타겟블록-name:S1,weight:50,size:100,길이리스트:[10, 10, 10, 10],최장길이:10,최소길이:10,최소착수요구일:2024-02-15,표준공기:5

*** 가능정반 :{'A': Timestamp('2024-02-15 00:00:00', freq='D'), 'B': Timestamp('2024-02-09 00:00:00', freq='D')}
*** 최선조기착수 가능정반:2024-02-09 00:00:00 ---> ['B']

>>>B정반의 면적_최장길이 적합도 함수 체크
>>>>>정반면적리스트:[150], 정반길이리스트:[15, 15, 10, 10], 블록사이즈:100, 블록최장길이:10, 블록최단길이:10
>>>>>정반 B의 면적/사이즈 배치가능 여부:['적합'] / 정반가능중량:100 정반면적:150.0, 길이리스트:[15, 15, 10, 10], 정반최장길이:15

*** 물리적 스펙 가능 정반: ['B']

*** 랜덤선택최선정반:B
*** 랜덤정반스펙- 길이리스트:[15, 15, 10, 10], 면적리스트:[150], MIN면적:150, block_size:100, 잔여면적:50, 잔여면적비율:0.33

>>>잔여면적비율 30.0%로 30% 이상이므로 정반 쪼개기 - 자식정반이름 :B_57 / 자식정반면적:50.0 / 엄마정반면적: 100.0
*** 새정반길이리스트: [10, 10, 5, 5]

*** 수정정반리스트: ['A', 'B', 'C', 'A_29', 'A_98', 'C_73', 'B_57']
*** 최종배정결과 : {'블록명': 'S1', '정반명': 'B', '착수일': '2024-02-09'}

???????????배정된정반: ['B', 'A', 'A', 'C', 'B']
(블록배치전) 수정블록리스트 : ['S1', 'S3', 'S7'], 수정정반리스트 : ['A', 'B', 'C', 'A_29', 'A_98', 'C_73', 'B_57']
(블록배치후) 수정블록리스트 : ['S3', 'S7'], 수정정반리스트 : ['A', 'B', 'C', 'A_29', 'A_98', 'C_73', 'B_57']
==========================================================================================

*** 타겟블록-name:S3,weight:30,size:30,길이리스트:[6, 6, 5, 5],최장길이:6,최소길이:5,최소착수요구일:2024-02-06,표준공기:4

*** 가능정반 :{'C': Timestamp('2024-02-06 00:00:00', freq='D'), 'A_29': Timestamp('2024-02-03 00:00:00', freq='D')}
*** 최선조기착수 가능정반:2024-02-03 00:00:00 ---> ['A_29']

>>>A_29정반의 면적_최장길이 적합도 함수 체크
>>>>>정반면적리스트:[80], 정반길이리스트:[10, 10, 8, 8], 블록사이즈:30, 블록최장길이:6, 블록최단길이:5
>>>>>정반 A_29의 면적/사이즈 배치가능 여부:['적합'] / 정반가능중량:100 정반면적:80.0, 길이리스트:[10, 10, 8, 8], 정반최장길이:10

*** 물리적 스펙 가능 정반: ['A_29']

*** 랜덤선택최선정반:A_29
*** 랜덤정반스펙- 길이리스트:[10, 10, 8, 8], 면적리스트:[80], MIN면적:80, block_size:30, 잔여면적:50, 잔여면적비율:0.62

>>>잔여면적비율 60.0%로 30% 이상이므로 정반 쪼개기 - 자식정반이름 :A_29_35 / 자식정반면적:50.0 / 엄마정반면적: 30.0
*** 새정반길이리스트: [8, 10, 3, 4]

*** 수정정반리스트: ['A', 'B', 'C', 'A_29', 'A_98', 'C_73', 'B_57', 'A_29_35']
*** 최종배정결과 : {'블록명': 'S3', '정반명': 'A_29', '착수일': '2024-02-03'}

???????????배정된정반: ['B', 'A', 'A', 'C', 'B', 'A_29']
(블록배치전) 수정블록리스트 : ['S3', 'S7'], 수정정반리스트 : ['A', 'B', 'C', 'A_29', 'A_98', 'C_73', 'B_57', 'A_29_35']
(블록배치후) 수정블록리스트 : ['S7'], 수정정반리스트 : ['A', 'B', 'C', 'A_29', 'A_98', 'C_73', 'B_57', 'A_29_35']
==========================================================================================

*** 타겟블록-name:S7,weight:30,size:30,길이리스트:[6, 6, 5, 5],최장길이:6,최소길이:5,최소착수요구일:2024-02-17,표준공기:4

*** 가능정반 :{'A': Timestamp('2024-02-15 00:00:00', freq='D'), 'B': Timestamp('2024-02-14 00:00:00', freq='D'), 'C': Timestamp('2024-02-06 00:00:00', freq='D'), 'A_29': Timestamp('2024-02-07 00:00:00', freq='D'), 'A_98': Timestamp('2024-02-09 00:00:00', freq='D'), 'B_57': Timestamp('2024-02-09 00:00:00', freq='D'), 'A_29_35': Timestamp('2024-02-15 00:00:00', freq='D')}
*** 최선조기착수 가능정반:2024-02-06 00:00:00 ---> ['C']

>>>C정반의 면적_최장길이 적합도 함수 체크
>>>>>정반면적리스트:[50], 정반길이리스트:[10, 10, 5, 5], 블록사이즈:30, 블록최장길이:6, 블록최단길이:5
>>>>>정반 C의 면적/사이즈 배치가능 여부:['적합'] / 정반가능중량:30 정반면적:50.0, 길이리스트:[10, 10, 5, 5], 정반최장길이:10

*** 물리적 스펙 가능 정반: ['C']

*** 랜덤선택최선정반:C
*** 랜덤정반스펙- 길이리스트:[10, 10, 5, 5], 면적리스트:[50], MIN면적:50, block_size:30, 잔여면적:20, 잔여면적비율:0.4

>>>잔여면적비율 40.0%로 30% 이상이므로 정반 쪼개기 - 자식정반이름 :C_80 / 자식정반면적:20.0 / 엄마정반면적: 30.0
*** 새정반길이리스트: [5, 5, 4, 4]

*** 수정정반리스트: ['A', 'B', 'C', 'A_29', 'A_98', 'C_73', 'B_57', 'A_29_35', 'C_80']
*** 최종배정결과 : {'블록명': 'S7', '정반명': 'C', '착수일': '2024-02-06'}

???????????배정된정반: ['B', 'A', 'A', 'C', 'B', 'A_29', 'C']
(블록배치전) 수정블록리스트 : ['S7'], 수정정반리스트 : ['A', 'B', 'C', 'A_29', 'A_98', 'C_73', 'B_57', 'A_29_35', 'C_80']
(블록배치후) 수정블록리스트 : [], 수정정반리스트 : ['A', 'B', 'C', 'A_29', 'A_98', 'C_73', 'B_57', 'A_29_35', 'C_80']
==========================================================================================

100%|██████████████████████████████████████████████████████████████████| 8/8 [00:00<00:00, 28.78it/s]

In [139]:
배치결과 = result[0]
배치결과 = 배치결과[["블록명", "정반구분", "정반명", "착수일", "표준공기", "종료일", "조립중량"]].sort_values(by="정반구분")
배치결과

  블록명 정반구분   정반명         착수일  표준공기         종료일  조립중량
1  S2    A     A  2024-02-03     6  2024-02-09    60
2  S8    A     A  2024-02-09     6  2024-02-15    60
5  S3    A  A_29  2024-02-03     4  2024-02-07    30
0  S6    B     B  2024-02-03     6  2024-02-09    50
4  S1    B     B  2024-02-09     5  2024-02-14    50
3  S4    C     C  2024-02-03     3  2024-02-06    20
6  S7    C     C  2024-02-06     4  2024-02-10    30

In [140]:
@unpack_df_columns
def create_text(블록명, 표준공기):
    return str(블록명)+" / "+"조립중량: "+str(표준공기)+"ton"

In [141]:
배치결과["차트텍스트"] = 배치결과[["블록명","표준공기"]].apply(create_text, axis=1)
배치결과

  블록명 정반구분   정반명         착수일  표준공기         종료일  조립중량            차트텍스트
1  S2    A     A  2024-02-03     6  2024-02-09    60  S2 / 조립중량: 6ton
2  S8    A     A  2024-02-09     6  2024-02-15    60  S8 / 조립중량: 6ton
5  S3    A  A_29  2024-02-03     4  2024-02-07    30  S3 / 조립중량: 4ton
0  S6    B     B  2024-02-03     6  2024-02-09    50  S6 / 조립중량: 6ton
4  S1    B     B  2024-02-09     5  2024-02-14    50  S1 / 조립중량: 5ton
3  S4    C     C  2024-02-03     3  2024-02-06    20  S4 / 조립중량: 3ton
6  S7    C     C  2024-02-06     4  2024-02-10    30  S7 / 조립중량: 4ton

In [142]:
draw_gant(배치결과)

In [143]:
새정반리스트 = result[2].sort_values(by="정반구분")
새정반리스트 = 새정반리스트[["정반구분", "정반명", "가능중량", "사이즈", "중량순서", "크기순서", 
                 "우선순위", "원길이리스트", "원최장길이", "원최소길이", "원면적리스트", 
                 "수정길이리스트", "수정최장길이", "수정최소길이", "수정면적리스트"]]
새정반리스트

,정반구분,정반명,가능중량,사이즈,중량순서,크기순서,우선순위,원길이리스트,원최장길이,원최소길이,원면적리스트,수정길이리스트,수정최장길이,수정최소길이,수정면적리스트
0,A,A,100,200.0,3.5,1.0,0.8,"[20, 20, 10, 10]",20,10,[200],None,None,None,None
3,A,A_29,100,80.0,3.5,3.5,1.4,"[10, 10, 8, 8]",10,8,[80],"[10, 10, 8, 8]",10,8,[80]
4,A,A_98,100,80.0,3.5,3.5,1.4,"[10, 10, 8, 8]",10,8,[80],"[10, 10, 8, 8]",10,8,[80]
7,A,A_29_35,100,50.0,3.5,6.0,2.0,"[8, 10, 3, 4]",10,3,"[32, 30]","[8, 10, 3, 4]",10,3,"[32, 30]"
1,B,B,100,150.0,3.5,2.0,1.0,"[15, 15, 10, 10]",15,10,[150],None,None,None,None
6,B,B_57,100,50.0,3.5,6.0,2.0,"[10, 10, 5, 5]",10,5,[50],"[10, 10, 5, 5]",10,5,[50]
2,C,C,30,50.0,8.0,6.0,2.7,"[10, 10, 5, 5]",10,5,[50],None,None,None,None
5,C,C_73,30,20.0,8.0,8.5,3.3,"[5, 5, 4, 4]",5,4,[20],"[5, 5, 4, 4]",5,4,[20]
8,C,C_80,30,20.0,8.0,8.5,3.3,"[5, 5, 4, 4]",5,4,[20],"[5, 5, 4, 4]",5,4,[20]

In [144]:
배치후블록데이터 = result[1]
배치후블록데이터

,블록명,중량,표준공기,납기,정반배치,사이즈,최소요구착수일,날짜순서,공기순서,크기순서,우선순위,길이리스트,최장길이,최소길이
5,S6,50,6,2024-02-11,1,120,2024-02-05,2.0,3.0,2.5,1.6,"[12, 12, 10, 10]",12,10
1,S2,60,6,2024-02-12,1,120,2024-02-06,3.5,3.0,2.5,1.9,"[12, 12, 10, 10]",12,10
4,S5,50,7,2024-02-15,0,120,2024-02-08,5.0,1.0,2.5,1.9,"[12, 12, 10, 10]",12,10
7,S8,60,6,2024-02-28,1,120,2024-02-22,8.0,3.0,2.5,2.9,"[12, 12, 10, 10]",12,10
3,S4,20,3,2024-02-06,1,30,2024-02-03,1.0,8.0,7.0,3.2,"[6, 6, 5, 5]",6,5
0,S1,50,5,2024-02-20,1,100,2024-02-15,6.0,5.0,5.0,3.4,"[10, 10, 10, 10]",10,10
2,S3,30,4,2024-02-10,1,30,2024-02-06,3.5,6.5,7.0,3.5,"[6, 6, 5, 5]",6,5
6,S7,30,4,2024-02-21,1,30,2024-02-17,7.0,6.5,7.0,4.3,"[6, 6, 5, 5]",6,5

In [145]:
배치후배치달력 = result[3]
배치후배치달력

            A  B  C  A_29  A_98  C_73  B_57  A_29_35  C_80
2024-02-01  1  1  1     1     1     1     1        1     1
2024-02-02  1  1  1     1     1     1     1        1     1
2024-02-03  1  1  1     1     1     0     1        1     1
2024-02-04  1  1  1     1     1     0     1        1     1
2024-02-05  1  1  1     1     1     0     1        1     1
2024-02-06  1  1  1     1     1     0     1        1     0
2024-02-07  1  1  1     0     1     0     1        1     0
2024-02-08  1  1  1     0     1     0     1        1     0
2024-02-09  1  1  1     0     0     0     0        1     0
2024-02-10  1  1  0     0     0     0     0        1     0
2024-02-11  1  1  0     0     0     0     0        1     0
2024-02-12  1  1  0     0     0     0     0        1     0
2024-02-13  1  1  0     0     0     0     0        1     0
2024-02-14  1  0  0     0     0     0     0        1     0
2024-02-15  0  0  0     0     0     0     0        0     0
2024-02-16  0  0  0     0     0     0     0        0     0
2024-02-17  0  0  0     0     0     0     0        0     0
2024-02-18  0  0  0     0     0     0     0        0     0
2024-02-19  0  0  0     0     0     0     0        0     0
2024-02-20  0  0  0     0     0     0     0        0     0
2024-02-21  0  0  0     0     0     0     0        0     0
2024-02-22  0  0  0     0     0     0     0        0     0
2024-02-23  0  0  0     0     0     0     0        0     0
2024-02-24  0  0  0     0     0     0     0        0     0
2024-02-25  0  0  0     0     0     0     0        0     0
2024-02-26  0  0  0     0     0     0     0        0     0
2024-02-27  0  0  0     0     0     0     0        0     0
2024-02-28  0  0  0     0     0     0     0        0     0

In [146]:
배치후공기달력 = result[4]
배치후공기달력

               A     B     C  A_29  A_98  C_73  B_57  A_29_35  C_80
2024-02-01   0.0   0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0
2024-02-02   0.0   0.0   0.0   0.0   0.0   0.0   0.0      0.0   0.0
2024-02-03   0.0   0.0   0.0   0.0   0.0  26.0   0.0      0.0   0.0
2024-02-04   0.0   0.0   0.0   0.0   0.0  25.0   0.0      0.0   0.0
2024-02-05   0.0   0.0   0.0   0.0   0.0  24.0   0.0      0.0   0.0
2024-02-06   0.0   0.0   0.0   0.0   0.0  23.0   0.0      0.0  23.0
2024-02-07   0.0   0.0   0.0  22.0   0.0  22.0   0.0      0.0  22.0
2024-02-08   0.0   0.0   0.0  21.0   0.0  21.0   0.0      0.0  21.0
2024-02-09   0.0   0.0   0.0  20.0  20.0  20.0  20.0      0.0  20.0
2024-02-10   0.0   0.0  19.0  19.0  19.0  19.0  19.0      0.0  19.0
2024-02-11   0.0   0.0  18.0  18.0  18.0  18.0  18.0      0.0  18.0
2024-02-12   0.0   0.0  17.0  17.0  17.0  17.0  17.0      0.0  17.0
2024-02-13   0.0   0.0  16.0  16.0  16.0  16.0  16.0      0.0  16.0
2024-02-14   0.0  15.0  15.0  15.0  15.0  15.0  15.0      0.0  15.0
2024-02-15  14.0  14.0  14.0  14.0  14.0  14.0  14.0     14.0  14.0
2024-02-16  13.0  13.0  13.0  13.0  13.0  13.0  13.0     13.0  13.0
2024-02-17  12.0  12.0  12.0  12.0  12.0  12.0  12.0     12.0  12.0
2024-02-18  11.0  11.0  11.0  11.0  11.0  11.0  11.0     11.0  11.0
2024-02-19  10.0  10.0  10.0  10.0  10.0  10.0  10.0     10.0  10.0
2024-02-20   9.0   9.0   9.0   9.0   9.0   9.0   9.0      9.0   9.0
2024-02-21   8.0   8.0   8.0   8.0   8.0   8.0   8.0      8.0   8.0
2024-02-22   7.0   7.0   7.0   7.0   7.0   7.0   7.0      7.0   7.0
2024-02-23   6.0   6.0   6.0   6.0   6.0   6.0   6.0      6.0   6.0
2024-02-24   5.0   5.0   5.0   5.0   5.0   5.0   5.0      5.0   5.0
2024-02-25   4.0   4.0   4.0   4.0   4.0   4.0   4.0      4.0   4.0
2024-02-26   3.0   3.0   3.0   3.0   3.0   3.0   3.0      3.0   3.0
2024-02-27   2.0   2.0   2.0   2.0   2.0   2.0   2.0      2.0   2.0
2024-02-28   1.0   1.0   1.0   1.0   1.0   1.0   1.0      1.0   1.0

In [147]:
배치후공백순서달력 = result[5]
배치후공백순서달력

            A  B  C  A_29  A_98  C_73  B_57  A_29_35  C_80
2024-02-01  0  0  0     0     0     0     0        0     0
2024-02-02  0  0  0     0     0     0     0        0     0
2024-02-03  0  0  0     0     0     1     0        0     0
2024-02-04  0  0  0     0     0     0     0        0     0
2024-02-05  0  0  0     0     0     0     0        0     0
2024-02-06  0  0  0     0     0     0     0        0     1
2024-02-07  0  0  0     1     0     0     0        0     0
2024-02-08  0  0  0     0     0     0     0        0     0
2024-02-09  0  0  0     0     1     0     1        0     0
2024-02-10  0  0  1     0     0     0     0        0     0
2024-02-11  0  0  0     0     0     0     0        0     0
2024-02-12  0  0  0     0     0     0     0        0     0
2024-02-13  0  0  0     0     0     0     0        0     0
2024-02-14  0  1  0     0     0     0     0        0     0
2024-02-15  1  0  0     0     0     0     0        1     0
2024-02-16  0  0  0     0     0     0     0        0     0
2024-02-17  0  0  0     0     0     0     0        0     0
2024-02-18  0  0  0     0     0     0     0        0     0
2024-02-19  0  0  0     0     0     0     0        0     0
2024-02-20  0  0  0     0     0     0     0        0     0
2024-02-21  0  0  0     0     0     0     0        0     0
2024-02-22  0  0  0     0     0     0     0        0     0
2024-02-23  0  0  0     0     0     0     0        0     0
2024-02-24  0  0  0     0     0     0     0        0     0
2024-02-25  0  0  0     0     0     0     0        0     0
2024-02-26  0  0  0     0     0     0     0        0     0
2024-02-27  0  0  0     0     0     0     0        0     0
2024-02-28  0  0  0     0     0     0     0        0     0

In [148]:
정반스펙달력 = result[6]
정반스펙달력

,A,B,C,A_29,A_98,C_73,B_57,A_29_35,C_80
2024-02-01,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]","[10, 10, 8, 8]","[10, 10, 8, 8]","[5, 5, 4, 4]","[10, 10, 5, 5]","[8, 10, 3, 4]","[5, 5, 4, 4]"
2024-02-02,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]","[10, 10, 8, 8]","[10, 10, 8, 8]","[5, 5, 4, 4]","[10, 10, 5, 5]","[8, 10, 3, 4]","[5, 5, 4, 4]"
2024-02-03,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]","[10, 10, 8, 8]","[10, 10, 8, 8]",None,"[10, 10, 5, 5]","[8, 10, 3, 4]","[5, 5, 4, 4]"
2024-02-04,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]","[10, 10, 8, 8]","[10, 10, 8, 8]",None,"[10, 10, 5, 5]","[8, 10, 3, 4]","[5, 5, 4, 4]"
2024-02-05,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]","[10, 10, 8, 8]","[10, 10, 8, 8]",None,"[10, 10, 5, 5]","[8, 10, 3, 4]","[5, 5, 4, 4]"
2024-02-06,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]","[10, 10, 8, 8]","[10, 10, 8, 8]",None,"[10, 10, 5, 5]","[8, 10, 3, 4]",None
2024-02-07,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,"[10, 10, 8, 8]",None,"[10, 10, 5, 5]","[8, 10, 3, 4]",None
2024-02-08,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,"[10, 10, 8, 8]",None,"[10, 10, 5, 5]","[8, 10, 3, 4]",None
2024-02-09,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,"[8, 10, 3, 4]",None
2024-02-10,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,"[8, 10, 3, 4]",None
2024-02-11,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,"[8, 10, 3, 4]",None
2024-02-12,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,"[8, 10, 3, 4]",None
2024-02-13,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,"[8, 10, 3, 4]",None
2024-02-14,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,"[8, 10, 3, 4]",None
2024-02-15,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None
2024-02-16,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None
2024-02-17,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None
2024-02-18,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None
2024-02-19,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None
2024-02-20,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None
2024-02-21,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None
2024-02-22,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None
2024-02-23,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None
2024-02-24,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None
2024-02-25,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None
2024-02-26,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None
2024-02-27,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None
2024-02-28,"[20, 20, 10, 10]","[15, 15, 10, 10]","[10, 10, 5, 5]",None,None,None,None,None,None

### 메모
- 정반명이 정반구분명하고 같아지는 오류
- 달력상 자식정반명 중복 발생하는 문제.... 무시해도 되나??